---
services:
  watchtower:
    image: docker.io/containrrr/watchtower:latest
    restart: unless-stopped
    labels:
      com.centurylinklabs.watchtower.enable: true
    environment:
      WATCHTOWER_CLEANUP: true
      WATCHTOWER_LABEL_ENABLE: true
    volumes:
      - /run/docker.sock:/var/run/docker.sock:ro

  tabby:
    image: docker.io/tabbyml/tabby:latest
    restart: unless-stopped
    labels:
      com.centurylinklabs.watchtower.enable: true
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities:
                - gpu
    command:
      - serve
      - --device
      - cuda
      - --model
      - StarCoder-3B
    ports:
      - 6060:8080
    volumes:
      - /mnt/shared/tabby:/data
