---
services:
  tabby:
    image: docker.io/tabbyml/tabby:latest
    restart: unless-stopped
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities:
                - gpu
    command:
      - serve
      - --model
      - TabbyML/DeepseekCoder-6.7B
      - --device
      - cuda
    ports:
      - "8080:8080"
    volumes:
      - /mnt/tabby:/data

  # sonarqube:
  #   image: docker.io/library/sonarqube:community
  #   restart: unless-stopped
  #   ports:
  #     - 9000:9000
  #   volumes:
  #     - /mnt/sonarqube/data:/opt/sonarqube/data
  #     - /mnt/sonarqube/logs:/opt/sonarqube/logs
