---
services:
  tabby:
    image: docker.io/tabbyml/tabby:latest
    restart: unless-stopped
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities:
                - gpu
    command:
      - serve
      - --device
      - cuda
      - --model
      - TabbyML/DeepseekCoder-6.7B
    ports:
      - 8080:8080
    volumes:
      - /mnt/tabby:/data

  sonarqube:
    image: docker.io/library/sonarqube:latest
    restart: unless-stopped
    ports:
      - 9000:9000
    volumes:
      - /mnt/sonarqube/data:/opt/sonarqube/data
      - /mnt/sonarqube/extensions:/opt/sonarqube/extensions
      - logs:/opt/sonarqube/logs

volumes:
  logs:
