---
services:
  tabby:
    image: docker.io/tabbyml/tabby:latest
    restart: unless-stopped
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities:
                - gpu
    command:
      - serve
      - --device
      - cuda
      - --model
      - TabbyML/DeepseekCoder-6.7B
    ports:
      - 8080:8080
    volumes:
      - /mnt/tabby:/data

volumes:
  logs:
