#!/usr/bin/env bash

set -eu
set -o pipefail


LIB="$(dirname "$(dirname "$(realpath "$0")")")/lib/fsautocomplete"
cd "$LIB" || exit 1


ARGS=(
  dotnet
  tool
  run
  dotnet-fsautocomplete
  --background-service-enabled
  )


exec dotnet "${ARGS[@]}"

