---
- bin: sortd
  args:
    - ${filetype}
  type: stream
  filetypes:
    - cfg
  install:
    pip:
      - sortd

- bin: sortd
  args:
    - json
  type: stream
  filetypes:
    - json
    - jsonc

- bin: taplo
  args:
    - format
    - --option=align_entries=true
    - --option=array_trailing_comma=true
    - --option=reorder_keys=true
    - --
    - ${tmpname}
  type: fs
  filetypes:
    - toml

- bin: shfmt
  args:
    - --indent=${tabsize}
  type: stream
  filetypes:
    - sh
    - zsh
  install:
    script:
      file: shfmt.sh

- bin: pwsh-fmt.ps1
  args: []
  type: stream
  filetypes:
    - ps1

- bin: prolog-fmt
  args: []
  type: stream
  filetypes:
    - prolog

- bin: stylish-haskell
  args: []
  type: stream
  filetypes:
    - haskell
  install:
    script:
      file: stylish.dl.hs
      required:
        - runhaskell

- bin: systemd-fmt
  args: []
  type: stream
  filetypes:
    - systemd

- bin: perltidy
  args:
    - --indent-columns=2
  type: stream
  filetypes:
    - perl

- bin: dockerfile-utils
  args:
    - format
    - --spaces
    - ${tabsize}
    - ${tmpname}
  type: stream
  filetypes:
    - dockerfile

- bin: isort
  args:
    - --profile=black
    - --filename=${filename}
    - --
    - "-"
  type: stream
  filetypes:
    - python
  install:
    pip:
      - isort

- bin: black
  args:
    - --stdin-filename=${filename}
    - --
    - "-"
  type: stream
  filetypes:
    - python
  install:
    pip:
      - black

- bin: cljfmt
  args:
    - fix
    - --remove-multiple-non-indenting-spaces
    - --sort-ns-references
    - --split-keypairs-over-multiple-lines
    - --
    - ${tmpname}
  type: fs
  filetypes:
    - clojure
  install:
    script:
      file: clj_fmt.clj
      required:
        - clojure

- bin: csscomb
  args:
    - --
    - ${tmpname}
  type: stream
  filetypes:
    - css
  install:
    npm:
      - csscomb

- bin: prettier
  args:
    - --stdin-filepath=${filename}
    - --tab-width=${tabsize}
    # - --plugin=@prettier/plugin-xml
    # - --plugin=prettier-plugin-tailwindcss
    # - --plugin=prettier-plugin-organize-imports
    - --
  type: stream
  filetypes:
    - awk
    - css
    - graphql
    - html
    - javascript*
    - json*
    - less
    - liquid
    - markdown
    - php
    - scss
    - typescript*
    - xml
    - yaml*
  install:
    npm:
      # - "@prettier/plugin-php"
      # - prettier-plugin-awk
      # - prettier-plugin-tailwindcss
      - "@prettier/plugin-xml"
      - prettier
      - prettier-plugin-organize-imports

- bin: stree
  args:
    - format
    # plugin/single_quotes,
    - --plugins=plugin/trailing_comma
    - --
    - ${tmpname}
  type: stream
  env:
    NO_COLOR: "1"
  filetypes:
    - rbs
    - ruby
  install:
    gem:
      - syntax_tree

- bin: rubocop
  args:
    - --fail-level=fatal
    - --stderr
    - --stdin
    - --format=quiet
    - --no-color
    - --autocorrect
  type: stream
  filetypes:
    - ruby
  install:
    gem:
      - rubocop

- bin: luafmt
  args:
    - --line-width=80
    - --indent-count=${tabsize}
    - --write-mode=replace
    - --
    - ${tmpname}
  type: fs
  filetypes:
    - lua
  install:
    npm:
      - lua-fmt

- bin: rustfmt
  args:
    - --edition=2021
  type: stream
  filetypes:
    - rust

- bin: gofmt
  args:
    - -w
    - --
    - ${tmpname}
  type: fs
  filetypes:
    - go

- bin: clang-format
  args: []
  type: stream
  filetypes:
    - c
    - cpp

- bin: fprettify
  args: []
  type: stream
  filetypes:
    - fortran
  install:
    pip:
      - fprettify

- bin: latexindent
  args:
    - --overwrite
    - --
    - ${tmpname}
  filetypes:
    - plaintex
    - tex
  type: fs
  install:
    script:
      file: latexindent.dl.pl
      required:
        - perl
        - cpanm

- bin: fantomas
  args:
    - --
    - ${tmpname}
  type: fs
  filetypes:
    - fsharp
  install:
    script:
      file: fantomas.dl.fsx
      required:
        - dotnet

- bin: ktfmt
  args:
    - --
    - ${tmpname}
  type: fs
  filetypes:
    - kotlin
  install:
    script:
      file: ktfmt.dl.kts
      required:
        - kotlinc

- bin: javafmt
  args:
    - "-"
  type: stream
  filetypes:
    - java
  install:
    script:
      file: javafmt.dl.sh

- bin: styler
  args:
    - ${tmpname}
  type: fs
  filetypes:
    - r
  install:
    script:
      file: styler.dl.r
      required:
        - Rscript
        - R

- bin: sql-formatter
  args:
    # - --uppercase
    # - --lines-between-queries=2
    # - --indent=${tabsize}
    - --language=postgresql
    - --output=${tmpname}
    - --
    - ${tmpname}
  type: fs
  filetypes:
    - sql
  install:
    npm:
      - sql-formatter
