---
- bin: sortd
  args:
    - ${filetype}
  type: stream
  filetypes:
    - json
    - cfg
  install:
    pip:
      - sortd

- bin: isort
  type: stream
  args:
    - --profile
    - black
    - --
    - "-"
  filetypes:
    - python
  install:
    pip:
      - isort

- bin: black
  type: stream
  args:
    - --stdin-filename
    - ${filename}
    - --
    - "-"
  filetypes:
    - python
  install:
    pip:
      - black

- bin: import-sort
  args:
    - --write
    - --
    - ${tmpname}
  type: fs
  filetypes:
    - javascript*
    - typescript*
  install:
    npm:
      - import-sort-cli

- bin: prettier
  args:
    - --stdin-filepath
    - ${filename}
    - --
  type: stream
  filetypes:
    - css
    - html
    - javascript*
    - json*
    - less
    - markdown
    - scss
    - typescript*
    - xml
    - yaml*
  install:
    npm:
      - prettier

- bin: luafmt
  type: stream
  args:
    - --stdin
    - --line-width=80
    - --indent-count=${tabsize}
  filetypes:
    - lua
  install:
    npm:
      - lua-fmt

- bin: rustfmt
  type: stream
  args:
    - --edition
    - "2018"
  filetypes:
    - rust

- bin: gofmt
  type: stream
  filetypes:
    - go

- bin: latexindent
  type: stream
  args: []
  filetypes:
    - plaintex
    - tex
  install:
    script:
      required:
        - git
        - perl
      env:
        URI: https://github.com/cmhughes/latexindent.pl
        TAG: "V3.11"
      file: dl_latex_format.sh

- bin: pg_format
  type: stream
  args:
    - --spaces=${tabsize}
    - --comma-break
    - --nogrouping
    - --function-case=0
  filetypes:
    - sql
  install:
    script:
      required:
        - git
        - perl
      env:
        URI: https://github.com/darold/pgFormatter
        TAG: "v4.4"
      file: dl_pg_format.sh
