---
- bin: sortd
  args:
    - ${filetype}
  type: stream
  filetypes:
    - json
    - toml
    - cfg
  install:
    pip:
      - sortd

- bin: isort
  args:
    - --profile
    - black
    - --
    - ${tmpname}
  type: fs
  filetypes:
    - python
  install:
    pip:
      - isort

- bin: black
  args:
    - --
    - ${tmpname}
  type: fs
  filetypes:
    - python
  install:
    pip:
      - black

# - bin: import-sort
#   args:
#     - --write
#     - --
#     - ${tmpname}
#   type: fs
#   filetypes:
#     - javascript*
#     - typescript*
#   install:
#     npm:
#       - import-sort-cli

- bin: csscomb
  args:
    - --
    - ${tmpname}
  type: stream
  filetypes:
    - css
  install:
    npm:
      - csscomb

- bin: prettier
  args:
    - --stdin-filepath
    - ${filename}
    - --
  type: stream
  filetypes:
    - css
    - html
    - javascript*
    - json*
    - less
    - markdown
    - php
    - rbs
    - ruby
    - scss
    - typescript*
    - xml
    - yaml*
  install:
    npm:
      - prettier
      - "@prettier/plugin-php"
      - "@prettier/plugin-ruby"
      - "@prettier/plugin-xml"

- bin: luafmt
  args:
    - --line-width=80
    - --indent-count=${tabsize}
    - --write-mode=replace
    - --
    - ${tmpname}
  type: fs
  filetypes:
    - lua
  install:
    npm:
      - lua-fmt

- bin: rustfmt
  args:
    - --edition=2018
  type: stream
  filetypes:
    - rust

- bin: gofmt
  args:
    - -w
    - --
    - ${tmpname}
  type: fs
  filetypes:
    - go

- bin: latexindent
  args:
    - --overwrite
    - --
    - ${tmpname}
  type: fs
  filetypes:
    - plaintex
    - tex
  install:
    script:
      required:
        - git
        - perl
      env:
        URI: https://github.com/cmhughes/latexindent.pl
        TAG: "V3.11"
      file: dl/latex_format.sh

- bin: r-fmt
  type: fs
  args:
    - ${tmpname}
  filetypes:
    - r
  install:
    script:
      required:
        - Rscript
        - R
      file: dl/rfmt.sh

# - bin: shfmt
#   type: fs
#   args:
#     - -w
#     - ${tmpname}
#   filetypes:
#     - sh
#     - zsh
#   install:
#     go:
#       - mvdan.cc/sh/v3/cmd/shfmt@latest

# - bin: pg_format
#   args:
#     - --spaces=${tabsize}
#     - --comma-break
#     - --nogrouping
#     - --function-case=0
#     - --output=${tmpname}
#     - --
#     - ${tmpname}
#   type: fs
#   filetypes:
#     - sql
#   install:
#     script:
#       required:
#         - git
#         - perl
#       env:
#         URI: https://github.com/darold/pgFormatter
#         TAG: "v5.0"
#       file: dl/pg_format.sh

- bin: sql-formatter
  args:
    - --uppercase
    - --lines-between-queries=2
    - --indent=${tabsize}
    - --output=${tmpname}
    - --
    - ${tmpname}
  type: fs
  filetypes:
    - sql
  install:
    npm:
      - sql-formatter
