---
- bin: sortd
  args:
    - ${filetype}
  type: stream
  filetypes:
    - json
    - cfg
  install:
    pip:
      - sortd

- bin: isort
  type: stream
  args:
    - "-"
  filetypes:
    - python
  install:
    pip:
      - isort

- bin: black
  type: stream
  args:
    - "-"
  filetypes:
    - python
  install:
    pip:
      - black

- bin: import-sort
  args:
    - --write
    - --
    - ${tmpname}
  type: fs
  filetypes:
    - javascript
    - javascript.jsx
    - typescript
    - typescript.tsx
    - typescriptreact
  install:
    npm:
      - import-sort-cli

- bin: prettier
  args:
    - --stdin-filepath
    - ${filename}
    - --
  type: stream
  filetypes:
    - css
    - html
    - javascript
    - javascript.jsx
    - json
    - jsonc
    - javascriptreact
    - less
    - markdown
    - scss
    - typescript
    - typescript.tsx
    - typescriptreact
    - xml
    - yaml
    - yaml.ansible
    - yaml.docker-compose
  install:
    npm:
      - prettier

- bin: pg_format
  type: stream
  args:
    - --spaces=${tabsize}
    - --comma-break
    - --nogrouping
    - --function-case=0
  filetypes:
    - sql
  install:
    script:
      required:
        - git
        - perl
      env:
        URI: https://github.com/darold/pgFormatter
        TAG: "v4.4"
      file: dl_pg_format.sh

- bin: rustfmt
  type: stream
  filetypes:
    - rust

- bin: gofmt
  type: stream
  filetypes:
    - go

- bin: luafmt
  type: stream
  args:
    - --stdin
    - --line-width=80
    - --indent-count=${tabsize}
  filetypes:
    - lua
  install:
    npm:
      - lua-fmt

