---
- args:
    - ${filetype}
  bin: sortd
  filetypes:
    - cfg
    - json
  install:
    pip:
      - sortd
  type: stream

- args:
    - format
    - --option=align_entries=true
    - --option=array_trailing_comma=true
    - --option=reorder_keys=true
    - --
    - ${tmpname}
  bin: taplo
  filetypes:
    - toml
  type: fs

- args:
    - --indent=${tabsize}
  bin: shfmt
  filetypes:
    - sh
    - zsh
  install:
    go:
      - mvdan.cc/sh/v3/cmd/shfmt@latest
  type: stream

- args: []
  bin: pwsh-fmt.ps1
  filetypes:
    - ps1
  type: stream

- args: []
  bin: prolog-fmt
  filetypes:
    - prolog
  type: stream

- args: []
  bin: systemd-fmt
  filetypes:
    - systemd
  type: stream

- args:
    - --indent-columns=2
  bin: perltidy
  filetypes:
    - perl
  type: stream

- args:
    - format
    - --spaces
    - ${tabsize}
    - ${tmpname}
  bin: dockerfile-utils
  filetypes:
    - dockerfile
  type: stream

- args:
    - --profile=black
    - --filename=${filename}
    - --
    - "-"
  bin: isort
  filetypes:
    - python
  install:
    pip:
      - isort
  type: stream

- args:
    - --stdin-filename=${filename}
    - --
    - "-"
  bin: black
  filetypes:
    - python
  install:
    pip:
      - black
  type: stream

- args:
    - --
    - ${tmpname}
  bin: csscomb
  filetypes:
    - css
  install:
    npm:
      - csscomb
  type: stream

- args:
    - --stdin-filepath=${filename}
    - --tab-width=${tabsize}
    - --
  bin: prettier
  filetypes:
    - awk
    - css
    - graphql
    - html
    - java
    - javascript*
    - json*
    - less
    - liquid
    - markdown
    - php
    - scss
    - typescript*
    - xml
    - yaml*
  install:
    npm:
      # - prettier-plugin-awk
      - prettier
      - "@prettier/plugin-php"
      - "@prettier/plugin-xml"
      - "@shopify/prettier-plugin-liquid"
      - prettier-plugin-java
      - prettier-plugin-organize-imports
      # - prettier-plugin-tailwindcss
  type: stream

- args:
    - format
    - --
    - ${tmpname}
  bin: stree
  env:
    NO_COLOR: "1"
  filetypes:
    - rbs
    - ruby
  install:
    gem:
      - syntax_tree
  type: stream

- args:
    - --fail-level=fatal
    - --no-color
    - --autocorrect
    - --
    - ${tmpname}
  bin: rubocop
  filetypes:
    - ruby
  install:
    gem:
      - rubocop
  type: fs

- args:
    - --line-width=80
    - --indent-count=${tabsize}
    - --write-mode=replace
    - --
    - ${tmpname}
  bin: luafmt
  filetypes:
    - lua
  install:
    npm:
      - lua-fmt
  type: fs

- args:
    - --edition=2021
  bin: rustfmt
  filetypes:
    - rust
  type: stream

- args:
    - -w
    - --
    - ${tmpname}
  bin: gofmt
  filetypes:
    - go
  type: fs

- args: []
  bin: clang-format
  filetypes:
    - c
    - cpp
  type: stream

- args:
    - --overwrite
    - --
    - ${tmpname}
  bin: latexindent
  filetypes:
    - plaintex
    - tex
  install:
    script:
      env:
        URI: https://github.com/cmhughes/latexindent.pl/archive/V3.11.tar.gz
      file: dl/latex_format.pl
      required:
        - perl
        - cpanm
  type: fs

- args:
    - --
    - ${tmpname}
  bin: fantomas
  filetypes:
    - fsharp
  install:
    script:
      file: dl/fantomas.fsx
      required:
        - dotnet
  type: fs

- args:
    - --
    - ${tmpname}
  bin: ktfmt
  filetypes:
    - kotlin
  install:
    script:
      env:
        URI: https://repo1.maven.org/maven2/com/facebook/ktfmt
      file: dl/ktfmt.kts
      required:
        - kotlinc
  type: fs

- args:
    - ${tmpname}
  bin: r-fmt
  filetypes:
    - r
  install:
    script:
      file: dl/rfmt.r
      required:
        - Rscript
        - R
  type: fs

- args:
    # - --uppercase
    # - --lines-between-queries=2
    # - --indent=${tabsize}
    - --language=postgresql
    - --output=${tmpname}
    - --
    - ${tmpname}
  bin: sql-formatter
  filetypes:
    - sql
  install:
    npm:
      - sql-formatter
  type: fs
