---
- bin: sortd
  args:
    - ${filetype}
  type: stream
  filetypes:
    - cfg
    - json
  install:
    pip:
      - sortd

- bin: taplo
  args:
    - format
    - --option=align_entries=true
    - --option=array_trailing_comma=true
    - --option=reorder_keys=true
    - --
    - ${tmpname}
  type: fs
  filetypes:
    - toml

- bin: shfmt
  type: stream
  args:
    - --indent=${tabsize}
  filetypes:
    - sh
    - zsh
  install:
    go:
      - mvdan.cc/sh/v3/cmd/shfmt@latest

- bin: pwsh-fmt.ps1
  args: []
  type: stream
  filetypes:
    - ps1

- bin: prolog-fmt
  type: stream
  args: []
  filetypes:
    - prolog

- bin: systemd-fmt
  type: stream
  args: []
  filetypes:
    - systemd

- bin: perltidy
  args:
    - --indent-columns=2
  type: stream
  filetypes:
    - perl

- bin: dockerfile-utils
  args:
    - format
    - --spaces
    - ${tabsize}
    - ${tmpname}
  type: stream
  filetypes:
    - dockerfile

- bin: isort
  args:
    - --profile=black
    - --filename=${filename}
    - --
    - "-"
  type: stream
  filetypes:
    - python
  install:
    pip:
      - isort

- bin: black
  args:
    - --stdin-filename=${filename}
    - --
    - "-"
  type: stream
  filetypes:
    - python
  install:
    pip:
      - black

- bin: csscomb
  args:
    - --
    - ${tmpname}
  type: stream
  filetypes:
    - css
  install:
    npm:
      - csscomb

- bin: prettier
  args:
    - --stdin-filepath=${filename}
    - --tab-width=${tabsize}
    - --
  type: stream
  filetypes:
    - awk
    - css
    - graphql
    - html
    - java
    - javascript*
    - json*
    - less
    - liquid
    - markdown
    - php
    - scss
    - typescript*
    - xml
    - yaml*
  install:
    npm:
      # - prettier-plugin-awk
      - prettier
      - "@prettier/plugin-php"
      - "@prettier/plugin-xml"
      - "@shopify/prettier-plugin-liquid"
      - prettier-plugin-java
      - prettier-plugin-organize-imports
      # - prettier-plugin-tailwindcss

- bin: stree
  args:
    - format
    - --
    - ${tmpname}
  env:
    NO_COLOR: "1"
  type: stream
  filetypes:
    - rbs
    - ruby
  install:
    gem:
      - syntax_tree

- bin: rubocop
  type: fs
  args:
    - --fail-level=fatal
    - --no-color
    - --autocorrect
    - --
    - ${tmpname}
  filetypes:
    - ruby
  install:
    gem:
      - rubocop

- bin: luafmt
  args:
    - --line-width=80
    - --indent-count=${tabsize}
    - --write-mode=replace
    - --
    - ${tmpname}
  type: fs
  filetypes:
    - lua
  install:
    npm:
      - lua-fmt

- bin: rustfmt
  args:
    - --edition=2021
  type: stream
  filetypes:
    - rust

- bin: gofmt
  args:
    - -w
    - --
    - ${tmpname}
  type: fs
  filetypes:
    - go

- bin: clang-format
  args: []
  type: stream
  filetypes:
    - c
    - cpp

- bin: latexindent
  args:
    - --overwrite
    - --
    - ${tmpname}
  type: fs
  filetypes:
    - plaintex
    - tex
  install:
    script:
      required:
        - perl
        - cpanm
      env:
        URI: https://github.com/cmhughes/latexindent.pl/archive/V3.11.tar.gz
      file: dl/latex_format.pl

- bin: fantomas
  type: fs
  args:
    - --
    - ${tmpname}
  filetypes:
    - fsharp
  install:
    script:
      required:
        - dotnet
      file: dl/fantomas.fsx

- bin: ktfmt
  type: fs
  args:
    - --
    - ${tmpname}
  filetypes:
    - kotlin
  install:
    script:
      required:
        - kotlinc
      env:
        URI: https://repo1.maven.org/maven2/com/facebook/ktfmt
      file: dl/ktfmt.kts

- bin: r-fmt
  type: fs
  args:
    - ${tmpname}
  filetypes:
    - r
  install:
    script:
      required:
        - Rscript
        - R
      file: dl/rfmt.r

- bin: sql-formatter
  args:
    # - --uppercase
    # - --lines-between-queries=2
    # - --indent=${tabsize}
    - --language=postgresql
    - --output=${tmpname}
    - --
    - ${tmpname}
  type: fs
  filetypes:
    - sql
  install:
    npm:
      - sql-formatter
