---
- bin: sortd
  args:
    - cfg
  type: stream
  filetypes:
    - cfg
    - confini
    - ini
  install:
    pip:
      - sortd

- bin: sortd
  args:
    - json
  type: stream
  filetypes:
    - json
    - jsonc

# - bin: sortd
#   args:
#     - toml
#   type: stream
#   filetypes:
#     - gitconfig

- bin: taplo
  args:
    - format
    - --option=align_entries=true
    - --option=array_trailing_comma=true
    - --option=reorder_keys=true
    - --
    - "-"
  type: stream
  filetypes:
    - gitconfig
    - toml

- bin: shfmt
  args:
    - --indent=${tabsize}
  type: stream
  filetypes:
    - env
    - sh
    - zsh
  install:
    requires:
      - jq
    script:
      file: shfmt.sh

- bin: pwsh-fmt.ps1
  args: []
  type: stream
  filetypes:
    - ps1

- bin: prolog-fmt.pro
  args: []
  type: stream
  filetypes:
    - prolog

- bin: stylish-haskell
  args: []
  type: stream
  filetypes:
    - haskell
  install:
    requires:
      - jq
      - runhaskell
    script:
      file: stylish.dl.hs

- bin: systemd-fmt.sh
  args: []
  type: stream
  filetypes:
    - systemd

- bin: perltidy.pl
  args:
    - --indent-columns=2
  type: stream
  filetypes:
    - perl

- bin: dockerfile-utils
  args:
    - format
    - --spaces
    - ${tabsize}
    - ${tmpname}
  type: stream
  filetypes:
    - dockerfile

- bin: isort
  args:
    - --profile=black
    - --filename=${filename}
    - --
    - "-"
  type: stream
  filetypes:
    - python
  install:
    pip:
      - isort

- bin: black
  args:
    - --stdin-filename=${filename}
    - --
    - "-"
  type: stream
  filetypes:
    - python
  install:
    pip:
      - black

- bin: cljfmt
  args:
    - fix
    - --remove-multiple-non-indenting-spaces
    - --sort-ns-references
    - --split-keypairs-over-multiple-lines
    - --
    - "-"
  type: stream
  filetypes:
    - clojure
  install:
    requires:
      - clojure
    script:
      file: clj_fmt.clj

# - bin: csscomb
#   args:
#     - --
#     - ${tmpname}
#   type: stream
#   filetypes:
#     - css
#   install:
#     npm:
#       - csscomb

- bin: prettier.js
  args:
    - ${filetype}
    - ${filename}
    - ${tabsize}
  type: stream
  filetypes:
    - awk
    - css
    - graphql
    - html
    - javascript*
    - json*
    - less
    - liquid
    - markdown
    - nginx
    - php
    - scss
    - typescript*
    - xml
    - yaml*
  install:
    npm:
      # - prettier-plugin-awk
      - "@prettier/plugin-php"
      - "@prettier/plugin-xml"
      - prettier
      - prettier-plugin-nginx
      - prettier-plugin-organize-imports
      - prettier-plugin-tailwindcss
    requires:
      - node
    script:
      file: prettier.dl.js

- bin: stree
  args:
    - format
    # plugin/single_quotes,
    - --plugins=plugin/trailing_comma
    - --
    - ${tmpname}
  type: stream
  env:
    NO_COLOR: "1"
  filetypes:
    - rbs
    - ruby
  install:
    gem:
      - syntax_tree

- bin: rubocop.rb
  args:
    - ${filename}
    - --fail-level=fatal
    - --stderr
    - --stdin
    - --format=quiet
    - --no-color
    - --autocorrect
  type: stream
  filetypes:
    - ruby

- bin: luafmt
  args:
    - --line-width=80
    - --indent-count=${tabsize}
    - --stdin
  type: stream
  filetypes:
    - lua
  install:
    npm:
      - lua-fmt

- bin: rustfmt
  args:
    - --edition=2021
  type: stream
  filetypes:
    - rust

- bin: goimports
  type: stream
  filetypes:
    - go
  install:
    requires:
      - go
    script:
      file: goimports.go

- bin: gofmt
  args:
    - -s
    - -w
    - --
    - ${tmpname}
  type: fs
  filetypes:
    - go

- bin: clang-format
  args:
    - --Werror
    - --assume-filename=${filename}
  type: stream
  filetypes:
    - c
    - cpp
    - cs
    - objc

- bin: fprettify
  args: []
  type: stream
  filetypes:
    - fortran
  install:
    pip:
      - fprettify

- bin: latexindent.pl
  args: []
  filetypes:
    - plaintex
    - tex
  type: stream
  install:
    requires:
      - gcc
      - jq
      - perl
    script:
      file: latexindent.dl.pl

- bin: fantomas.fsx
  args:
    - ${tmpname}
  type: fs
  filetypes:
    - fsharp
  install:
    requires:
      - dotnet
    script:
      file: fantomas.dl.fsx

- bin: ktfmt.java
  args:
    - --
    - "-"
  type: stream
  filetypes:
    - kotlin
  install:
    requires:
      - kotlinc
    script:
      file: ktfmt.dl.kts

- bin: javafmt.java
  args:
    - "-"
  type: stream
  filetypes:
    - java
  install:
    requires:
      - java
      - jq
    script:
      file: javafmt.dl.java

- bin: styler.r
  args:
    - ${tmpname}
  type: fs
  filetypes:
    - r
  install:
    requires:
      - Rscript
      - R
    script:
      file: styler.dl.r

- bin: sql-formatter
  args:
    # - --uppercase
    # - --lines-between-queries=2
    # - --indent=${tabsize}
    - --language=postgresql
  type: stream
  filetypes:
    - sql
  install:
    npm:
      - sql-formatter

- bin: eslint.js
  args:
    - ${filename}
    - ${tmpname}
  type: fs
  filetypes:
    - javascript*
    - typescript*
  install:
    requires:
      - node
    script:
      file: eslint.dl.js

- bin: terraform
  args:
    - fmt
    - "-"
  type: stream
  filetypes:
    - hcl
    - terraform
