---
- args:
    - ${filetype}
  bin: sortd
  filetypes:
    - cfg
  install:
    pip:
      - sortd
  type: stream

- args:
    - json
  bin: sortd
  filetypes:
    - json
    - jsonc
  type: stream

- args:
    - format
    - --option=align_entries=true
    - --option=array_trailing_comma=true
    - --option=reorder_keys=true
    - --
    - ${tmpname}
  bin: taplo
  filetypes:
    - toml
  type: fs

- args:
    - --indent=${tabsize}
  bin: shfmt
  filetypes:
    - sh
    - zsh
  install:
    script:
      env:
        DARWIN_URI: https://github.com/mvdan/sh/releases/latest/download/shfmt_v3.6.0_darwin_arm64
        LINUX_URI: https://github.com/mvdan/sh/releases/latest/download/shfmt_v3.6.0_linux_amd64
        NT_URI: https://github.com/mvdan/sh/releases/latest/download/shfmt_v3.6.0_windows_amd64.exe
      file: dl/shfmt.sh
  type: stream

- args: []
  bin: pwsh-fmt.ps1
  filetypes:
    - ps1
  type: stream

- args: []
  bin: prolog-fmt
  filetypes:
    - prolog
  type: stream

- args: []
  bin: systemd-fmt
  filetypes:
    - systemd
  type: stream

- args:
    - --indent-columns=2
  bin: perltidy
  filetypes:
    - perl
  type: stream

- args:
    - format
    - --spaces
    - ${tabsize}
    - ${tmpname}
  bin: dockerfile-utils
  filetypes:
    - dockerfile
  type: stream

- args:
    - --profile=black
    - --filename=${filename}
    - --
    - "-"
  bin: isort
  filetypes:
    - python
  install:
    pip:
      - isort
  type: stream

- args:
    - --stdin-filename=${filename}
    - --
    - "-"
  bin: black
  filetypes:
    - python
  install:
    pip:
      - black
  type: stream

- args:
    - fix
    - --remove-multiple-non-indenting-spaces
    - --sort-ns-references
    - --split-keypairs-over-multiple-lines
    - --
    - ${tmpname}
  bin: cljfmt
  filetypes:
    - clojure
  install:
    script:
      env:
        DARWIN_URI: https://github.com/weavejester/cljfmt/releases/latest/download/cljfmt-0.10.4-darwin-aarch64.tar.gz
        LINUX_URI: https://github.com/weavejester/cljfmt/releases/latest/download/cljfmt-0.10.4-linux-amd64-static.tar.gz
        NT_URI: https://github.com/weavejester/cljfmt/releases/latest/download/cljfmt-0.10.4-win-amd64.zip
      file: dl/clj_fmt.clj
      required:
        - clojure
  type: fs

- args:
    - --
    - ${tmpname}
  bin: csscomb
  filetypes:
    - css
  install:
    npm:
      - csscomb
  type: stream

- args:
    - --stdin-filepath=${filename}
    - --tab-width=${tabsize}
    - --
  bin: prettier
  filetypes:
    - awk
    - css
    - graphql
    - html
    - java
    - javascript*
    - json*
    - less
    - liquid
    - markdown
    - php
    - scss
    - typescript*
    - xml
    - yaml*
  install:
    npm:
      # - prettier-plugin-awk
      - prettier
      - "@prettier/plugin-php"
      - "@prettier/plugin-xml"
      - "@shopify/prettier-plugin-liquid"
      - prettier-plugin-java
      - prettier-plugin-organize-imports
      # - prettier-plugin-tailwindcss
  type: stream

- args:
    - format
    - --plugins=plugin/single_quotes,plugin/trailing_comma
    - --
    - ${tmpname}
  bin: stree
  env:
    NO_COLOR: "1"
  filetypes:
    - rbs
    - ruby
  install:
    gem:
      - syntax_tree
  type: stream

# - args:
#     - --fail-level=fatal
#     - --stderr
#     - --stdin
#     - --format=quiet
#     - --no-color
#     - --autocorrect
#   bin: rubocop
#   filetypes:
#     - ruby
#   install:
#     gem:
#       - rubocop
#   type: stream

- args:
    - --line-width=80
    - --indent-count=${tabsize}
    - --write-mode=replace
    - --
    - ${tmpname}
  bin: luafmt
  filetypes:
    - lua
  install:
    npm:
      - lua-fmt
  type: fs

- args:
    - --edition=2021
  bin: rustfmt
  filetypes:
    - rust
  type: stream

- args:
    - -w
    - --
    - ${tmpname}
  bin: gofmt
  filetypes:
    - go
  type: fs

- args: []
  bin: clang-format
  filetypes:
    - c
    - cpp
  type: stream

- args:
    - --overwrite
    - --
    - ${tmpname}
  bin: latexindent
  filetypes:
    - plaintex
    - tex
  install:
    script:
      env:
        URI: https://github.com/cmhughes/latexindent.pl/archive/V3.11.tar.gz
      file: dl/latex_format.pl
      required:
        - perl
        - cpanm
  type: fs

- args:
    - --
    - ${tmpname}
  bin: fantomas
  filetypes:
    - fsharp
  install:
    script:
      file: dl/fantomas.fsx
      required:
        - dotnet
  type: fs

- args:
    - --
    - ${tmpname}
  bin: ktfmt
  filetypes:
    - kotlin
  install:
    script:
      env:
        URI: https://repo1.maven.org/maven2/com/facebook/ktfmt
      file: dl/ktfmt.kts
      required:
        - kotlinc
  type: fs

- args:
    - ${tmpname}
  bin: r-fmt
  filetypes:
    - r
  install:
    script:
      file: dl/rfmt.r
      required:
        - Rscript
        - R
  type: fs

- args:
    # - --uppercase
    # - --lines-between-queries=2
    # - --indent=${tabsize}
    - --language=postgresql
    - --output=${tmpname}
    - --
    - ${tmpname}
  bin: sql-formatter
  filetypes:
    - sql
  install:
    npm:
      - sql-formatter
  type: fs
