---
- git:
    uri: https://github.com/nvim-treesitter/nvim-treesitter
    branch: 0.5-compat
  vals:
    ts_opts:
      highlight:
        enable: True
      textobjects:
        select:
          enable: True
          keymaps:
            is: "@statement.outer"
            as: "@statement.outer"

            ib: "@block.inner"
            ab: "@block.outer"

            ia: "@parameter.inner"
            aa: "@parameter.outer"

            ic: "@conditional.inner"
            ac: "@conditional.outer"

            iC: "@class.inner"
            aC: "@class.outer"

            if: "@function.inner"
            af: "@function.outer"

            iF: "@call.inner"
            aF: "@call.outer"

            iL: "@loop.inner"
            aL: "@loop.outer"

  lua: |-
    require'nvim-treesitter.configs'.setup(vim.g.ts_opts)

- git:
    uri: https://github.com/nvim-treesitter/nvim-treesitter-textobjects
    branch: 0.5-compat

- git:
    uri: https://github.com/neovim/nvim-lspconfig

- git:
    uri: https://github.com/ms-jpq/chadtree
  keys:
    - modes: n
      maps:
        "<leader>v": "<cmd>CHADopen<cr>"

- git:
    uri: https://github.com/ms-jpq/coq_nvim
  vals:
    coq_settings:
      auto_start: True
      clients.snippets.user_path: "~/.config/snips/"
      keymap:
        repeat: "<leader>."
        eval_snips: "<leader>j"
  keys:
    - modes: n
      maps:
        "<leader>z": "<cmd>COQnow<cr>"
  lua: |-
    if vim.env.SSH_CONNECTION or vim.env.T9 then
      local cs = vim.g.coq_settings
      cs["clients.tabnine.enabled"] = true
      vim.g.coq_settings = cs
    end

- git:
    uri: https://github.com/ms-jpq/coq.artifacts

- git:
    uri: https://github.com/ms-jpq/coq.thirdparty
  lua: |-
    require("coq_3rd") {
      {src = "vimtex", short_name = "vTEX"}
    }

- git:
    uri: https://github.com/junegunn/fzf

- git:
    uri: https://github.com/junegunn/fzf.vim
  vals:
    fzf_buffers_jump: True
    fzf_preview_window: right:wrap
    fzf_layout:
      window:
        width: 0.9
        height: 0.9
  keys:
    - modes: n
      maps:
        "<leader>o": "<cmd>BLines<cr>"
        "<leader>p": "<cmd>Buffers<cr>"
        "<leader>P": "<cmd>Files<cr>"
    - modes: n
      opts:
        silent: False
      maps:
        "<leader>O": ":Rg "
  lua: |-
    local fzf_opts = vim.env.FZF_DEFAULT_OPTS
    local new_opts = (fzf_opts or "") .. " --no-border"
    vim.env.FZF_DEFAULT_OPTS = new_opts

- git:
    uri: https://github.com/rakr/vim-one
  lua: |-
    vim.cmd [[colorscheme one]]
    vim.opt.background = "light"

# - git:
#     uri: https://github.com/kosayoda/nvim-lightbulb
#   viml: |-
#     autocmd CursorHold,CursorHoldI * lua require'nvim-lightbulb'.update_lightbulb()

- git:
    uri: https://github.com/tpope/vim-repeat

- git:
    uri: https://github.com/tpope/vim-surround

- git:
    uri: https://github.com/junegunn/vim-easy-align
  keys:
    - modes: nv
      opts:
        noremap: False
      maps:
        "ga": "<plug>(EasyAlign)"

- git:
    uri: https://github.com/tpope/vim-unimpaired

- git:
    uri: https://github.com/mhinz/vim-signify

- git:
    uri: https://github.com/jpalardy/vim-slime
  vals:
    slime_target: tmux
    slime_no_mappings: True
    slime_default_config:
      socket_name: default
      target_pane: "{last}"
    slime_cell_delimiter: "# @@"
  keys:
    - modes: n
      opts:
        noremap: False
      maps:
        "<leader>s": "<Plug>SlimeSendCell"
    - modes: v
      opts:
        noremap: False
      maps:
        "<leader>s": "<Plug>SlimeRegionSend"
  viml: |-
    let g:slime_paste_file = tempname()

- git:
    uri: https://github.com/norcalli/nvim-colorizer.lua
  lua: |-
    local go, colourizer = pcall(require, "colorizer")
    if go then
      colourizer.setup()
    end

- git:
    uri: https://github.com/lervag/vimtex
  vals:
    vimtex_compiler_method: tectonic
    vimtex_view_enabled: false
