---
name: CI

on:
  push:
  schedule:
    - cron: "0 0 * * *" # daily

jobs:
  docker:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - run: |-
          make build

  ubuntu:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-python@v3

      - run: |-
          sudo -- apt-get update
          sudo -- apt-get install --no-install-recommends --yes -- swi-prolog cpanminus
          /home/linuxbrew/.linuxbrew/bin/brew install -- clojure/tools/clojure

      - run: |-
          gmake lint

      - run: |-
          eval -- "$(/home/linuxbrew/.linuxbrew/bin/brew shellenv)"
          env
          gmake install -- JAVA_HOME="$JAVA_HOME_17_X64"

  macos:
    runs-on: macos-latest

    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-python@v3

      - run: |-
          brew install -- bash make htmlq

      - run: |-
          gmake lint

      - run: |-
          gmake install -- JAVA_HOME="$JAVA_HOME_17_X64"

  windows:
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-python@v3

      - shell: bash
        run: |-
          # make install
          true
