---
name: CI

on:
  push:
  schedule:
    - cron: "0 0 * * *" # daily

jobs:
  docker:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - run: |-
          make build

  ubuntu:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-python@v3

      - run: |-
          sudo -- apt-get update
          sudo -- apt-get install --no-install-recommends --yes -- swi-prolog gnucobol
          /home/linuxbrew/.linuxbrew/bin/brew install -- clojure/tools/clojure
          eval -- "$(/home/linuxbrew/.linuxbrew/bin/brew shellenv)"
          CLJ="$(command -v -- clojure)"
          sudo -- ln -v -s -- "$CLJ" /usr/local/bin/clojure

      - run: |-
          gmake lint

      - env:
          {}
          # GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |-
          gmake install -- JAVA_HOME="$JAVA_HOME_17_X64"

  macos:
    runs-on: macos-latest

    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-python@v3

      - run: |-
          brew install -- bash make htmlq flock

      - run: |-
          gmake lint

      - env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |-
          gmake install -- JAVA_HOME="$JAVA_HOME_17_X64" NO_R=1

  windows:
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-python@v3
        # TODO: remove when python updates to 3.12.1
        with:
          python-version: "3.11"

      - run: |-
          Get-Command -- cpan
          Get-Command -- perl

      - run: |-
          $pacman = Join-Path -Path $Env:GHCUP_MSYS2 'usr' 'bin' 'pacman'
          $argv = @('--sync', '--refresh', '--noconfirm', '--', 'make')
          & $pacman @argv

      - run: |-
          $make = Join-Path -Path $Env:GHCUP_MSYS2 'usr' 'bin' 'make'
          & $make patch -- JAVA_HOME="$Env:JAVA_HOME_17_X64" NO_R=1
