---
on:
  push:
  schedule:
    - cron: "0 0 * * *" # daily

jobs:
  docker:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - run: |-
          make build

  ubuntu:
    # TODO: use ubuntu-latest
    runs-on: ubuntu-24.04

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5

      - run: |-
          sudo -- apt-get update
          sudo -- apt-get install --no-install-recommends --yes -- swi-prolog-nox gnucobol moreutils

      - run: |-
          /home/linuxbrew/.linuxbrew/bin/brew install -- clojure/tools/clojure
          eval -- "$(/home/linuxbrew/.linuxbrew/bin/brew shellenv)"
          CLJ="$(command -v -- clojure)"
          sudo -- ln -v -s -- "$CLJ" /usr/local/bin/clojure

      - run: |-
          gmake lint

      - env:
          {}
          # GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |-
          gmake install -- JAVA_HOME="$JAVA_HOME_17_X64"

  macos:
    runs-on: macos-latest

    steps:
      - uses: actions/checkout@v4

      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: "3.3"

      - run: |-
          brew install -- bash make flock htmlq moreutils

      - run: |-
          gmake lint

      - env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |-
          gmake install -- JAVA_HOME="$JAVA_HOME_17_X64" NO_R=1

  windows:
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-java@v4
        with:
          distribution: "microsoft"
          java-version: "21"

      - run: |-
          Get-Command -All -- perl
          Get-Command -All -- cpan

      - run: |-
          make patch -- JAVA_HOME="$Env:JAVA_HOME_21_X64" NO_R=1
