---
name: CI

on:
  push:
  schedule:
    - cron: "0 0 * * *" # daily

jobs:
  mypy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup Python
        uses: actions/setup-python@v3

      - run: |-
          make lint

  docker:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - run: |-
          make build

  install:
    strategy:
      matrix:
        platform:
          - ubuntu-latest
          - macos-latest
          # - windows-latest

    runs-on: ${{ matrix.platform }}

    steps:
      - uses: actions/checkout@v3

      - run: |-
          make install
